### PR TITLE
add Uploadcare

### PR DESCRIPTION
**Pull request by dmitry-mukhin**

### CODE REVIEW

**Comment by dmitry-mukhin** [comment]
validation fails on `heroku.json` and I don't think I want to touch that  🤷‍♂️

**Comment by Gdewilde** [comment]
@dmitry-mukhin thanks for taking the time to send this in. I will fix the validation afterward.

**Comment by dmitry-mukhin** [comment]
👍

**Comment by Gdewilde** [comment]
Online ✅

screen shot 2018-05-22 at 19 29 08

**Pull request merged**
